default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: book_mi_place_development

test:
  <<: *default
  database: book_mi_place_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
